### ISSUE TITLE
Q: compatibility with multiplexed libraries?

### ISSUE THREAD

**Issue by rebeelouise** [epi2me-labs/pychopper#4]
Hi, 

I saw on community a recommendation to use this with the multiplexed cDNA-PCR methods. However, don't see any usage on the README.md file. 

I just wanted your thoughts on compatibility and recommended usage if so!

Cheers.

**Comment by Benedikt-Brommer** [comment]
Hi,
I was wondering the same thing. 

We sort barcoded reads with Guppy and then split the contained fused reads with Pychopper.
Is there a way to remain the barcodes during the splitting in order to demultiplex after the splitting?

I am worried that fused reads stem from different samples. If those fused reads are split, we end up with several reads that we can't match to the correct sample anymore.

(Further explanation:
We use multiplexed libraries for RNA-Seq and keep pushing the amount of loaded samples and number of reads to increase our sequencing depth. Therefore, we get 20-30% of fused reads (chimeric reads)).

**Comment by nrhorner** [comment]
@rebeelouise Sorry for the late reply. 
If you are still interested in this, you should process each demultiplexed sample through Pychopper individually.

@Benedikt-Brommer Unfortunately there's no way to keep barcodes using Pychopper as they will be trimmed along wit the adapters.
